services:
  app:
    build: 
      context: .
      target: app
    container_name: pytest-running
    stdin_open: true
    tty: true
    restart: unless-stopped

  tests:
    build: 
      context: .
      target: test
    container_name: pytest-tests
    command: sh -c "python -m coverage run -m unittest discover -s test -p 'test_*.py' -v 
      && python -m coverage xml -o coverage.xml
      && python -m coverage report -m 
      && python -m coverage html"
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    restart: "no"
    volumes:
      - ./:/app
    profiles:
      - test